// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-northeast-1',
  aws_content_delivery_bucket: 'js-exam-20200117114110-hostingbucket-dev',
  aws_content_delivery_bucket_region: 'ap-northeast-1',
  aws_content_delivery_url:
    'http://js-exam-20200117114110-hostingbucket-dev.s3-website-ap-northeast-1.amazonaws.com',
  aws_cognito_identity_pool_id:
    'ap-northeast-1:3e4b6b4b-6d37-4064-b173-64cba35423dc',
  aws_cognito_region: 'ap-northeast-1',
  aws_user_pools_id: 'ap-northeast-1_tTKSmGU4x',
  aws_user_pools_web_client_id: '3piciq9h0fv9fl0n0pnq1bacaq',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://jk65mnqrn5avfgwmjf6b4rgrj4.appsync-api.ap-northeast-1.amazonaws.com/graphql',
  aws_appsync_region: 'ap-northeast-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsmobile;
